# -*- coding: utf-8 -*-
"""analise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hcdPJbEFtwYrwYueCZGkrQlRM6OucUaf
"""

import pandas as pd

tabela_clientes = pd.read_csv(r"/content/drive/MyDrive/Colab Notebooks/ClientesBanco.csv", encoding="latin1")
tabela_clientes = tabela_clientes.drop("CLIENTNUM", axis=1) #exclui coluna referida
display(tabela_clientes)

#tratamento base de dados
tabela_clientes = tabela_clientes.dropna() #exclui linha vazia
display(tabela_clientes.info()) #analisa os dados
display(tabela_clientes.describe())


#analise de dados

display(tabela_clientes["Categoria"].value_counts()) #calcular valores iguais
display(tabela_clientes["Categoria"].value_counts(normalize = True)) #faz porcentagem

#Analisar o 80/20

import plotly.express as px

#criar tabela
def criarColuna():
  for coluna in tabela_clientes:
     fig = px.histogram(tabela_clientes, x=coluna, color="Categoria")
     fig.show()


criarColuna()